const INIT_PHOTOS = 'INIT_PHOTOS';
const INIT_LAZY_PHOTOS = 'INIT_LAZY_PHOTOS';
const INIT_SEARCH_PHOTOS = 'INIT_SEARCH_PHOTOS';
const INIT_LAZY_SEARCH_PHOTOS = 'INIT_LAZY_SEARCH_PHOTOS';
const INIT_CLEAR_PHOTOS = 'INIT_CLEAR_PHOTOS';

const FETCH_PHOTOS_LOADING = 'FETCH_PHOTOS_LOADING';
const FETCH_PHOTOS_LAZY_LOADING = 'FETCH_PHOTOS_LAZY_LOADING';
const FETCH_PHOTOS_SUCCESS = 'FETCH_PHOTOS_SUCCESS';
const FETCH_PHOTOS_SEARCH_SUCCESS = 'FETCH_PHOTOS_SEARCH_SUCCESS';

const FETCH_PHOTOS_FAILD = 'FETCH_PHOTOS_FAILD';

export {
  INIT_PHOTOS,
  INIT_LAZY_PHOTOS,
  INIT_SEARCH_PHOTOS,
  INIT_LAZY_SEARCH_PHOTOS,
  INIT_CLEAR_PHOTOS,

  FETCH_PHOTOS_SUCCESS,
  FETCH_PHOTOS_SEARCH_SUCCESS,
  FETCH_PHOTOS_FAILD,
  FETCH_PHOTOS_LOADING,
  FETCH_PHOTOS_LAZY_LOADING
};
